repos:
  - repo: local
    hooks:
      - id: check-container-running
        name: check-container-running
        description: Check if container is running
        entry: bash scripts/precommit-docker-check.sh
        language: system
        pass_filenames: false
        always_run: true
        verbose: true

      - id: container-linting
        name: container-linting
        description: Run code formatting in container
        entry: bash scripts/run-in-container.sh "uv run isort . && uv run black . && uv run flake8 && uv run pylint **/*.py"
        language: system
        pass_filenames: false
        always_run: true
        verbose: true

      - id: container-small-tests
        name: container-small-tests
        description: Run small tests in container
        entry: bash scripts/run-in-container.sh "uv run pytest tests/small"
        language: system
        pass_filenames: false
        always_run: true
        verbose: true
