repos:
  - repo: local
    hooks:
      - id: linting
        name: linting
        description: Run isort black flake8 pylint
        entry: bash -c "make format"
        language: python
        pass_filenames: false
        always_run: true
        verbose: true

      - id: small-tests
        name: small-tests
        description: Small-sized tests
        entry: bash -c "make test-small"
        language: python
        pass_filenames: false
        always_run: true
        verbose: true
